name: Windows PHP CI with MariaDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v2

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mysqli, pdo_mysql

      - name: 📦 Install Composer dependencies
        run: composer install

      - name: Install MariaDB
        run: |
          choco install mariadb
          
      - name: 🔄️ Refresh ENV
        run: |
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

      - name: ⚡ Setup and Configure MariaDB
        run: |
          mysql -e "CREATE DATABASE IF NOT EXISTS online_judge;"
          mysql -e "CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'root';"
          mysql -e "GRANT ALL PRIVILEGES ON online_judge.* TO 'root'@'localhost';"
          mysql -e "FLUSH PRIVILEGES;"

      - name: Run tests
        run: composer test
