name: Windows PHP CI with MariaDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    services:
      mariadb:
        image: mariadb:11.6
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: online_judge
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mysqli, pdo_mysql
          tools: composer

      - name: 📦 Install dependencies
        run: composer install --no-progress --no-suggest

      - name: ⚡ Setup MariaDB
        run: |
          echo "Waiting for MariaDB to be ready..."
          sleep 10
          mysql -h 127.0.0.1 -u root --password=root -e "CREATE DATABASE IF NOT EXISTS online_judge;"
          mysql -h 127.0.0.1 -u root --password=root online_judge < online-judge-setup-database.sql
        shell: bash

      - name: 🛠️ Run Tests
        run: vendor/bin/phpunit
